/*
 * Copyright (c) 2026 Jason Crawford
 * SPDX-License-Identifier: AGPL-3.0-only
 *
 * test_erasure_rlnc.c - Tests for RLNC erasure coding (erasure/rlnc.c).
 *
 * Two tiers, matching docs/ERASURE_CODES_DESIGN.md section 7:
 *  - Encode is checked byte-exact against an independent GF(2^16) oracle
 *    (rlnc_kat.inc, generated by tools/gen_rlnc_kat using GF-Complete over
 *    poly 0x1100B).  This validates the field arithmetic and Y = C . X.
 *  - The RLNC-specific behavior that no external library shares (wire
 *    format, recoding, rank-tracking decode) is validated by self-
 *    consistency: encode/decode round-trips, rank progress, recode-then-
 *    decode equals direct decode, and generation-id handling.
 */

#include "rlnc.h"

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

static int tests_run = 0;
static int tests_passed = 0;

#define TEST(name)                                                             \
    do {                                                                       \
        tests_run++;                                                           \
        printf("  %-58s ", name);                                              \
    } while (0)

#define PASS()                                                                 \
    do {                                                                       \
        tests_passed++;                                                        \
        printf("[PASS]\n");                                                    \
    } while (0)

#define FAIL(msg)                                                              \
    do {                                                                       \
        printf("[FAIL] %s\n", msg);                                            \
    } while (0)

/* Layout matches the initializer emitted by tools/gen_rlnc_kat. */
struct rlnc_kat {
    int k;
    int symbol_bytes;
    int num_coded;
    uint8_t sources[64]; /* k * symbol_bytes bytes used */
    uint16_t coeffs[64]; /* num_coded * k coefficients used */
    uint8_t coded[128];  /* num_coded * symbol_bytes bytes used */
};

#include "rlnc_kat.inc"

#define NUM_KATS (sizeof(rlnc_kats) / sizeof(rlnc_kats[0]))

#define GEN_ID 0xABCD1234u

/* Deterministic GF(2^16) value for self-consistency inputs. */
static uint16_t
det_gf16(uint32_t a, uint32_t b)
{
    uint32_t v = a * 2654435761u + b * 40503u + 0x1234u;
    return (uint16_t)(v >> 13);
}

/* ========================================================================
 * Oracle: encode matches the GF(2^16) KATs
 * ======================================================================== */

static void
test_encode_matches_oracle(void)
{
    size_t t;

    TEST("RLNC encode matches GF(2^16) oracle KATs");
    for (t = 0; t < NUM_KATS; t++) {
        const struct rlnc_kat *kat = &rlnc_kats[t];
        size_t k = (size_t)kat->k, sb = (size_t)kat->symbol_bytes;
        int i;

        for (i = 0; i < kat->num_coded; i++) {
            uint8_t packet[256];

            if (voleith_rlnc_encode(GEN_ID, kat->sources, k, sb,
                                    &kat->coeffs[i * kat->k],
                                    packet) != VOLEITH_EC_OK) {
                FAIL("encode failed");
                return;
            }
            if (memcmp(voleith_rlnc_packet_payload(packet, k),
                       kat->coded + (size_t)i * sb, sb) != 0) {
                FAIL("coded payload != oracle");
                return;
            }
            if (voleith_rlnc_packet_gen_id(packet) != GEN_ID) {
                FAIL("gen id not written");
                return;
            }
        }
    }
    PASS();
}

/* ========================================================================
 * Self-consistency: encode -> decode round-trip
 * ======================================================================== */

/*
 * Builds a coded packet from sources using a coefficient row, into packet.
 * Coefficient row j stored at coeffs[j].
 */
static int
make_coded(uint8_t *packet, const uint8_t *sources, size_t k,
           size_t symbol_bytes, const voleith_gf16_t *coeffs)
{
    return voleith_rlnc_encode(GEN_ID, sources, k, symbol_bytes, coeffs,
                               packet);
}

static void
test_decode_roundtrip(void)
{
    const size_t k = 4, sb = 8;
    uint8_t sources[64];
    voleith_rlnc_decoder_t dec;
    size_t i, j, s, elems = sb / 2;

    TEST("RLNC decode recovers the generation (mixed coefficients)");
    for (j = 0; j < k; j++)
        for (s = 0; s < elems; s++)
            voleith_gf16_to_bytes(sources + j * sb + 2 * s,
                                  det_gf16((uint32_t)j, (uint32_t)s));

    if (voleith_rlnc_decoder_init(&dec, k, sb) != VOLEITH_EC_OK) {
        FAIL("decoder init failed");
        return;
    }

    /*
     * Unit lower-triangular coefficient matrix (1 on the diagonal, mixed
     * below): guaranteed rank k, with genuine mixing across sources.
     */
    for (i = 0; i < k; i++) {
        uint8_t packet[256];
        voleith_gf16_t coeffs[8];

        for (j = 0; j < k; j++) {
            if (j < i)
                coeffs[j] = (voleith_gf16_t)(det_gf16((uint32_t)i + 7,
                                                      (uint32_t)j + 1) |
                                             1u);
            else if (j == i)
                coeffs[j] = 1;
            else
                coeffs[j] = 0;
        }
        if (make_coded(packet, sources, k, sb, coeffs) != VOLEITH_EC_OK) {
            voleith_rlnc_decoder_free(&dec);
            FAIL("encode failed");
            return;
        }
        if (voleith_rlnc_decoder_add(&dec, packet) != 1) {
            voleith_rlnc_decoder_free(&dec);
            FAIL("symbol not innovative");
            return;
        }
    }

    if (!voleith_rlnc_decoder_is_complete(&dec)) {
        voleith_rlnc_decoder_free(&dec);
        FAIL("decoder not complete after k symbols");
        return;
    }
    {
        uint8_t recovered[64];
        if (voleith_rlnc_decoder_recover(&dec, recovered) != VOLEITH_EC_OK) {
            voleith_rlnc_decoder_free(&dec);
            FAIL("recover failed");
            return;
        }
        if (memcmp(recovered, sources, k * sb) != 0) {
            voleith_rlnc_decoder_free(&dec);
            FAIL("recovered != sources");
            return;
        }
    }
    voleith_rlnc_decoder_free(&dec);
    PASS();
}

static void
test_redundant_symbol(void)
{
    const size_t k = 3, sb = 4;
    uint8_t sources[64];
    uint8_t packet[256];
    voleith_rlnc_decoder_t dec;
    voleith_gf16_t coeffs[3];
    size_t j;

    TEST("RLNC repeated symbol is not innovative");
    for (j = 0; j < k * sb; j++)
        sources[j] = (uint8_t)(j * 37 + 5);
    for (j = 0; j < k; j++)
        coeffs[j] = (voleith_gf16_t)(det_gf16((uint32_t)j, 99) | 1u);

    if (voleith_rlnc_decoder_init(&dec, k, sb) != VOLEITH_EC_OK) {
        FAIL("decoder init failed");
        return;
    }
    make_coded(packet, sources, k, sb, coeffs);
    if (voleith_rlnc_decoder_add(&dec, packet) != 1) {
        voleith_rlnc_decoder_free(&dec);
        FAIL("first add not innovative");
        return;
    }
    if (voleith_rlnc_decoder_add(&dec, packet) != 0) {
        voleith_rlnc_decoder_free(&dec);
        FAIL("duplicate add reported innovative");
        return;
    }
    if (voleith_rlnc_decoder_rank(&dec) != 1) {
        voleith_rlnc_decoder_free(&dec);
        FAIL("rank changed on redundant symbol");
        return;
    }
    voleith_rlnc_decoder_free(&dec);
    PASS();
}

static void
test_recode_then_decode(void)
{
    const size_t k = 4, sb = 8;
    uint8_t sources[64];
    uint8_t base[4][256];
    const uint8_t *inputs[2];
    uint8_t recoded[256];
    voleith_rlnc_decoder_t dec;
    voleith_gf16_t mix[2];
    size_t i, j, s, elems = sb / 2;

    TEST("RLNC recode-then-decode equals direct decode");
    for (j = 0; j < k; j++)
        for (s = 0; s < elems; s++)
            voleith_gf16_to_bytes(sources + j * sb + 2 * s,
                                  det_gf16((uint32_t)j + 3, (uint32_t)s + 2));

    /* k independent coded symbols (unit lower-triangular). */
    for (i = 0; i < k; i++) {
        voleith_gf16_t coeffs[8];
        for (j = 0; j < k; j++) {
            if (j < i)
                coeffs[j] =
                    (voleith_gf16_t)(det_gf16((uint32_t)i + 5, (uint32_t)j) |
                                     1u);
            else if (j == i)
                coeffs[j] = 1;
            else
                coeffs[j] = 0;
        }
        make_coded(base[i], sources, k, sb, coeffs);
    }

    /* Recode the first two into one symbol with both mix coefficients set. */
    inputs[0] = base[0];
    inputs[1] = base[1];
    mix[0] = (voleith_gf16_t)(det_gf16(1, 1) | 1u);
    mix[1] = (voleith_gf16_t)(det_gf16(2, 2) | 1u);
    if (voleith_rlnc_recode(inputs, 2, k, sb, mix, recoded) != VOLEITH_EC_OK) {
        FAIL("recode failed");
        return;
    }

    /*
     * Feed the recoded symbol (carries a base[0] component) plus base[1..k-1].
     * That spans all k sources, so decode must recover the generation.
     */
    if (voleith_rlnc_decoder_init(&dec, k, sb) != VOLEITH_EC_OK) {
        FAIL("decoder init failed");
        return;
    }
    if (voleith_rlnc_decoder_add(&dec, recoded) != 1) {
        voleith_rlnc_decoder_free(&dec);
        FAIL("recoded symbol not innovative");
        return;
    }
    for (i = 1; i < k; i++)
        voleith_rlnc_decoder_add(&dec, base[i]);

    if (!voleith_rlnc_decoder_is_complete(&dec)) {
        voleith_rlnc_decoder_free(&dec);
        FAIL("not complete with recoded + base symbols");
        return;
    }
    {
        uint8_t recovered[64];
        voleith_rlnc_decoder_recover(&dec, recovered);
        if (memcmp(recovered, sources, k * sb) != 0) {
            voleith_rlnc_decoder_free(&dec);
            FAIL("recovered != sources after recode");
            return;
        }
    }
    voleith_rlnc_decoder_free(&dec);
    PASS();
}

static void
test_incomplete_recover(void)
{
    const size_t k = 3, sb = 4;
    uint8_t sources[64];
    uint8_t packet[256];
    uint8_t recovered[64];
    voleith_rlnc_decoder_t dec;
    voleith_gf16_t coeffs[3];
    size_t j;

    TEST("RLNC recover before rank k returns ERR_INCOMPLETE");
    for (j = 0; j < k * sb; j++)
        sources[j] = (uint8_t)(j + 1);
    for (j = 0; j < k; j++)
        coeffs[j] = (voleith_gf16_t)(det_gf16((uint32_t)j, 3) | 1u);

    if (voleith_rlnc_decoder_init(&dec, k, sb) != VOLEITH_EC_OK) {
        FAIL("decoder init failed");
        return;
    }
    make_coded(packet, sources, k, sb, coeffs);
    voleith_rlnc_decoder_add(&dec, packet); /* rank 1 of k=3 */

    if (voleith_rlnc_decoder_recover(&dec, recovered) !=
        VOLEITH_EC_ERR_INCOMPLETE) {
        voleith_rlnc_decoder_free(&dec);
        FAIL("expected ERR_INCOMPLETE");
        return;
    }
    voleith_rlnc_decoder_free(&dec);
    PASS();
}

static void
test_generation_mismatch(void)
{
    const size_t k = 3, sb = 4;
    uint8_t sources[64];
    uint8_t p1[256], p2[256];
    voleith_rlnc_decoder_t dec;
    voleith_gf16_t coeffs[3];
    size_t j;

    TEST("RLNC decoder rejects a foreign generation id");
    for (j = 0; j < k * sb; j++)
        sources[j] = (uint8_t)(j * 11 + 2);
    for (j = 0; j < k; j++)
        coeffs[j] = (voleith_gf16_t)(det_gf16((uint32_t)j, 7) | 1u);

    voleith_rlnc_encode(GEN_ID, sources, k, sb, coeffs, p1);
    voleith_rlnc_encode(GEN_ID ^ 0xFFu, sources, k, sb, coeffs, p2);

    if (voleith_rlnc_decoder_init(&dec, k, sb) != VOLEITH_EC_OK) {
        FAIL("decoder init failed");
        return;
    }
    if (voleith_rlnc_decoder_add(&dec, p1) != 1) {
        voleith_rlnc_decoder_free(&dec);
        FAIL("first add not innovative");
        return;
    }
    if (voleith_rlnc_decoder_add(&dec, p2) >= 0) {
        voleith_rlnc_decoder_free(&dec);
        FAIL("foreign generation accepted");
        return;
    }
    voleith_rlnc_decoder_free(&dec);
    PASS();
}

int
main(void)
{
    printf("=== RLNC erasure-coding tests ===\n");
    test_encode_matches_oracle();
    test_decode_roundtrip();
    test_redundant_symbol();
    test_recode_then_decode();
    test_incomplete_recover();
    test_generation_mismatch();

    printf("\n=== Results: %d/%d passed ===\n", tests_passed, tests_run);
    return (tests_passed == tests_run) ? 0 : 1;
}
