/*
 * Copyright (c) 2026 Jason Crawford
 * SPDX-License-Identifier: AGPL-3.0-only
 *
 * test_proof.c - End-to-end tests for the VOLEitH proof system
 *
 * Tests (CLAUDE.md Phase 8 requirements):
 *   1. Correct proof verifies
 *   2. Proof with wrong witness is rejected
 *   3. Modifying any byte of a valid proof causes rejection
 *   4. Different fs_seeds produce different (but both valid) proofs
 *   5. Empty circuit (trivial) proof round-trip
 *   6. voleith_vole_hash cross-check: hash of same input is deterministic
 *   7. voleith_proof_byte_size matches actual proof size
 */

#include "proof.h"
#include "vole_hash.h"
#include "prover.h"
#include "circuit.h"

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdint.h>
#include <limits.h>

/* ================================================================
 * Test helpers
 * ================================================================ */

static int g_pass = 0, g_fail = 0;

#define CHECK(cond, msg)                                                       \
    do {                                                                       \
        if (cond) {                                                            \
            printf("  PASS: %s\n", msg);                                       \
            g_pass++;                                                          \
        } else {                                                               \
            printf("  FAIL: %s (line %d)\n", msg, __LINE__);                   \
            g_fail++;                                                          \
        }                                                                      \
    } while (0)

/* Build a small AND circuit: x0 AND x1 = x2 (witness only)
 *   witness[0] = x0, witness[1] = x1, witness[2] = x0 AND x1
 *   assert_zero(x0 AND x1 XOR x2)  → trivially satisfied if x2 = x0&x1
 *   But more simply: just assert x0 AND x1 = x2 by constraining the output.
 *
 * We build: w0 = witness_bit(0), w1 = witness_bit(1)
 *           w2 = AND(w0, w1)     ← AND gate output is w2
 *   No explicit constraint needed: the AND gate output already IS the
 *   correct value by definition of the circuit evaluation.
 *
 *   Actually for a meaningful proof we need to constrain something.
 *   Let's make a circuit that proves knowledge of (a, b) such that
 *   (a AND b) XOR c = 0 where c is an instance bit.
 *
 *   Instance: c = a & b (public target)
 *   Witness: a, b
 *   Circuit:
 *     w0 = witness(0) = a
 *     w1 = witness(1) = b
 *     w2 = AND(w0, w1) = a & b
 *     w3 = instance(0) = c
 *     w4 = XOR(w2, w3) = (a&b) XOR c
 *     assert_zero(w4)
 */
static voleith_circuit_t *
build_and_circuit(void)
{
    voleith_circuit_t *c = voleith_circuit_new();
    if (!c)
        return NULL;

    wire_id w0 = voleith_circuit_add_witness(c);     /* a */
    wire_id w1 = voleith_circuit_add_witness(c);     /* b */
    wire_id w2 = voleith_circuit_add_and(c, w0, w1); /* a & b */
    wire_id w3 = voleith_circuit_add_instance(c);    /* c (public) */
    wire_id w4 = voleith_circuit_add_xor(c, w2, w3); /* (a&b) XOR c */
    voleith_circuit_assert_zero(c, w4);

    return c;
}

/* Build a slightly larger circuit with a chain of AND gates */
static voleith_circuit_t *
build_chain_circuit(int n_and)
{
    voleith_circuit_t *c = voleith_circuit_new();
    if (!c)
        return NULL;

    /* Add 2 witness bits: a, b */
    wire_id a = voleith_circuit_add_witness(c);
    wire_id b = voleith_circuit_add_witness(c);

    /* Chain: w = a & b, w = w & a, w = w & b, ... */
    wire_id w = voleith_circuit_add_and(c, a, b);
    for (int i = 1; i < n_and; i++) {
        wire_id next = (i % 2 == 0) ? voleith_circuit_add_and(c, w, a)
                                    : voleith_circuit_add_and(c, w, b);
        w = next;
    }

    /* Assert the final result is zero (forces a=0 or b=0) */
    voleith_circuit_assert_zero(c, w);

    return c;
}

/* ================================================================
 * Test: VOLEHash - faest-ref known-answer vectors (generated by diag_vole_hash.c)
 *
 * All three parameter sets, ell=200, sd=0x00..0xNN, x=0xaa..0xMM.
 * ================================================================ */

static void
test_vole_hash_tvs(void)
{
    printf("\n[vole_hash known-answer vectors]\n");

    /* lambda=128, ell=200: x is ellhat_bytes = (200+384)/8+2 = 75 bytes */
    {
        static const uint8_t sd[] = {
            0x00, 0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07, 0x08, 0x09, 0x0a,
            0x0b, 0x0c, 0x0d, 0x0e, 0x0f, 0x10, 0x11, 0x12, 0x13, 0x14, 0x15,
            0x16, 0x17, 0x18, 0x19, 0x1a, 0x1b, 0x1c, 0x1d, 0x1e, 0x1f, 0x20,
            0x21, 0x22, 0x23, 0x24, 0x25, 0x26, 0x27, 0x28, 0x29, 0x2a, 0x2b,
            0x2c, 0x2d, 0x2e, 0x2f, 0x30, 0x31, 0x32, 0x33, 0x34, 0x35, 0x36,
            0x37, 0x38, 0x39, 0x3a, 0x3b, 0x3c, 0x3d, 0x3e, 0x3f, 0x40, 0x41,
            0x42, 0x43, 0x44, 0x45, 0x46, 0x47, 0x48, 0x49, 0x4a, 0x4b, 0x4c,
            0x4d, 0x4e, 0x4f, 0x50, 0x51, 0x52, 0x53, 0x54, 0x55, 0x56, 0x57,
        };
        static const uint8_t x[] = {
            0xaa, 0xab, 0xac, 0xad, 0xae, 0xaf, 0xb0, 0xb1, 0xb2, 0xb3, 0xb4,
            0xb5, 0xb6, 0xb7, 0xb8, 0xb9, 0xba, 0xbb, 0xbc, 0xbd, 0xbe, 0xbf,
            0xc0, 0xc1, 0xc2, 0xc3, 0xc4, 0xc5, 0xc6, 0xc7, 0xc8, 0xc9, 0xca,
            0xcb, 0xcc, 0xcd, 0xce, 0xcf, 0xd0, 0xd1, 0xd2, 0xd3, 0xd4, 0xd5,
            0xd6, 0xd7, 0xd8, 0xd9, 0xda, 0xdb, 0xdc, 0xdd, 0xde, 0xdf, 0xe0,
            0xe1, 0xe2, 0xe3, 0xe4, 0xe5, 0xe6, 0xe7, 0xe8, 0xe9, 0xea, 0xeb,
            0xec, 0xed, 0xee, 0xef, 0xf0, 0xf1, 0xf2, 0xf3, 0xf4,
        };
        static const uint8_t expected_h[] = {
            0x71, 0x92, 0x98, 0x54, 0xe3, 0x84, 0xf3, 0x6a, 0xa5,
            0xdb, 0x7c, 0xd9, 0x62, 0x92, 0x62, 0x72, 0xaa, 0xa7,
        };
        uint8_t h[18];
        voleith_vole_hash(h, sd, x, 200, 128);
        CHECK(memcmp(h, expected_h, sizeof(expected_h)) == 0,
              "VOLEHash lambda=128 matches faest-ref");
    }

    /* lambda=192, ell=200 */
    {
        static const uint8_t sd[] = {
            0x00, 0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07, 0x08, 0x09, 0x0a,
            0x0b, 0x0c, 0x0d, 0x0e, 0x0f, 0x10, 0x11, 0x12, 0x13, 0x14, 0x15,
            0x16, 0x17, 0x18, 0x19, 0x1a, 0x1b, 0x1c, 0x1d, 0x1e, 0x1f, 0x20,
            0x21, 0x22, 0x23, 0x24, 0x25, 0x26, 0x27, 0x28, 0x29, 0x2a, 0x2b,
            0x2c, 0x2d, 0x2e, 0x2f, 0x30, 0x31, 0x32, 0x33, 0x34, 0x35, 0x36,
            0x37, 0x38, 0x39, 0x3a, 0x3b, 0x3c, 0x3d, 0x3e, 0x3f, 0x40, 0x41,
            0x42, 0x43, 0x44, 0x45, 0x46, 0x47, 0x48, 0x49, 0x4a, 0x4b, 0x4c,
            0x4d, 0x4e, 0x4f, 0x50, 0x51, 0x52, 0x53, 0x54, 0x55, 0x56, 0x57,
            0x58, 0x59, 0x5a, 0x5b, 0x5c, 0x5d, 0x5e, 0x5f, 0x60, 0x61, 0x62,
            0x63, 0x64, 0x65, 0x66, 0x67, 0x68, 0x69, 0x6a, 0x6b, 0x6c, 0x6d,
            0x6e, 0x6f, 0x70, 0x71, 0x72, 0x73, 0x74, 0x75, 0x76, 0x77, 0x78,
            0x79, 0x7a, 0x7b, 0x7c, 0x7d, 0x7e, 0x7f,
        };
        static const uint8_t x[] = {
            0xaa, 0xab, 0xac, 0xad, 0xae, 0xaf, 0xb0, 0xb1, 0xb2, 0xb3, 0xb4,
            0xb5, 0xb6, 0xb7, 0xb8, 0xb9, 0xba, 0xbb, 0xbc, 0xbd, 0xbe, 0xbf,
            0xc0, 0xc1, 0xc2, 0xc3, 0xc4, 0xc5, 0xc6, 0xc7, 0xc8, 0xc9, 0xca,
            0xcb, 0xcc, 0xcd, 0xce, 0xcf, 0xd0, 0xd1, 0xd2, 0xd3, 0xd4, 0xd5,
            0xd6, 0xd7, 0xd8, 0xd9, 0xda, 0xdb, 0xdc, 0xdd, 0xde, 0xdf, 0xe0,
            0xe1, 0xe2, 0xe3, 0xe4, 0xe5, 0xe6, 0xe7, 0xe8, 0xe9, 0xea, 0xeb,
            0xec, 0xed, 0xee, 0xef, 0xf0, 0xf1, 0xf2, 0xf3, 0xf4, 0xf5, 0xf6,
            0xf7, 0xf8, 0xf9, 0xfa, 0xfb, 0xfc, 0xfd, 0xfe, 0xff, 0x00, 0x01,
            0x02, 0x03, 0x04, 0x05, 0x06, 0x07, 0x08, 0x09, 0x0a, 0x0b, 0x0c,
        };
        static const uint8_t expected_h[] = {
            0x12, 0xab, 0x54, 0x6d, 0xc7, 0x52, 0xf3, 0x33, 0x1d,
            0x49, 0x7b, 0xd1, 0x0e, 0xc0, 0x61, 0xfc, 0x87, 0x01,
            0xfb, 0xbd, 0x76, 0x69, 0x37, 0xba, 0xc6, 0xc2,
        };
        uint8_t h[26];
        voleith_vole_hash(h, sd, x, 200, 192);
        CHECK(memcmp(h, expected_h, sizeof(expected_h)) == 0,
              "VOLEHash lambda=192 matches faest-ref");
    }

    /* lambda=256, ell=200 */
    {
        static const uint8_t sd[] = {
            0x00, 0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07, 0x08, 0x09, 0x0a,
            0x0b, 0x0c, 0x0d, 0x0e, 0x0f, 0x10, 0x11, 0x12, 0x13, 0x14, 0x15,
            0x16, 0x17, 0x18, 0x19, 0x1a, 0x1b, 0x1c, 0x1d, 0x1e, 0x1f, 0x20,
            0x21, 0x22, 0x23, 0x24, 0x25, 0x26, 0x27, 0x28, 0x29, 0x2a, 0x2b,
            0x2c, 0x2d, 0x2e, 0x2f, 0x30, 0x31, 0x32, 0x33, 0x34, 0x35, 0x36,
            0x37, 0x38, 0x39, 0x3a, 0x3b, 0x3c, 0x3d, 0x3e, 0x3f, 0x40, 0x41,
            0x42, 0x43, 0x44, 0x45, 0x46, 0x47, 0x48, 0x49, 0x4a, 0x4b, 0x4c,
            0x4d, 0x4e, 0x4f, 0x50, 0x51, 0x52, 0x53, 0x54, 0x55, 0x56, 0x57,
            0x58, 0x59, 0x5a, 0x5b, 0x5c, 0x5d, 0x5e, 0x5f, 0x60, 0x61, 0x62,
            0x63, 0x64, 0x65, 0x66, 0x67, 0x68, 0x69, 0x6a, 0x6b, 0x6c, 0x6d,
            0x6e, 0x6f, 0x70, 0x71, 0x72, 0x73, 0x74, 0x75, 0x76, 0x77, 0x78,
            0x79, 0x7a, 0x7b, 0x7c, 0x7d, 0x7e, 0x7f, 0x80, 0x81, 0x82, 0x83,
            0x84, 0x85, 0x86, 0x87, 0x88, 0x89, 0x8a, 0x8b, 0x8c, 0x8d, 0x8e,
            0x8f, 0x90, 0x91, 0x92, 0x93, 0x94, 0x95, 0x96, 0x97, 0x98, 0x99,
            0x9a, 0x9b, 0x9c, 0x9d, 0x9e, 0x9f, 0xa0, 0xa1, 0xa2, 0xa3, 0xa4,
            0xa5, 0xa6, 0xa7,
        };
        static const uint8_t x[] = {
            0xaa, 0xab, 0xac, 0xad, 0xae, 0xaf, 0xb0, 0xb1, 0xb2, 0xb3, 0xb4,
            0xb5, 0xb6, 0xb7, 0xb8, 0xb9, 0xba, 0xbb, 0xbc, 0xbd, 0xbe, 0xbf,
            0xc0, 0xc1, 0xc2, 0xc3, 0xc4, 0xc5, 0xc6, 0xc7, 0xc8, 0xc9, 0xca,
            0xcb, 0xcc, 0xcd, 0xce, 0xcf, 0xd0, 0xd1, 0xd2, 0xd3, 0xd4, 0xd5,
            0xd6, 0xd7, 0xd8, 0xd9, 0xda, 0xdb, 0xdc, 0xdd, 0xde, 0xdf, 0xe0,
            0xe1, 0xe2, 0xe3, 0xe4, 0xe5, 0xe6, 0xe7, 0xe8, 0xe9, 0xea, 0xeb,
            0xec, 0xed, 0xee, 0xef, 0xf0, 0xf1, 0xf2, 0xf3, 0xf4, 0xf5, 0xf6,
            0xf7, 0xf8, 0xf9, 0xfa, 0xfb, 0xfc, 0xfd, 0xfe, 0xff, 0x00, 0x01,
            0x02, 0x03, 0x04, 0x05, 0x06, 0x07, 0x08, 0x09, 0x0a, 0x0b, 0x0c,
            0x0d, 0x0e, 0x0f, 0x10, 0x11, 0x12, 0x13, 0x14, 0x15, 0x16, 0x17,
            0x18, 0x19, 0x1a, 0x1b, 0x1c, 0x1d, 0x1e, 0x1f, 0x20, 0x21, 0x22,
            0x23, 0x24,
        };
        static const uint8_t expected_h[] = {
            0x5e, 0x21, 0x83, 0x6e, 0xf6, 0xc0, 0xbb, 0x9f, 0x7a,
            0xb5, 0x64, 0x4b, 0xf5, 0x33, 0xd6, 0xe8, 0x44, 0xb1,
            0x01, 0xa1, 0x74, 0xcd, 0x40, 0xb3, 0xa1, 0x49, 0xe1,
            0xa2, 0xe1, 0x9c, 0x66, 0x99, 0x9f, 0xeb,
        };
        uint8_t h[34];
        voleith_vole_hash(h, sd, x, 200, 256);
        CHECK(memcmp(h, expected_h, sizeof(expected_h)) == 0,
              "VOLEHash lambda=256 matches faest-ref");
    }
}

/* ================================================================
 * Test: proof_byte_size matches actual proof
 * ================================================================ */

static void
test_proof_size(void)
{
    printf("\n[proof_byte_size]\n");

    voleith_circuit_t *c = build_and_circuit();
    if (!c) {
        printf("  SKIP: circuit alloc failed\n");
        return;
    }

    size_t ell = voleith_qs_ell(c);
    size_t computed = voleith_proof_byte_size(&voleith_params_em_128f, ell);

    /* Prove and check actual size */
    uint8_t witness[1] = {0};  /* a=0, b=0 → a&b=0, c=0 → valid */
    uint8_t instance[1] = {0}; /* c=0 */
    uint8_t fs_seed[16];
    memset(fs_seed, 0x42, sizeof(fs_seed));

    voleith_proof_t proof;
    memset(&proof, 0, sizeof(proof));
    int ret = voleith_prove(&proof, &voleith_params_em_128f, c, witness,
                            instance, fs_seed, sizeof(fs_seed));

    if (ret != 0) {
        printf("  FAIL: prove returned %d (line %d)\n", ret, __LINE__);
        g_fail++;
    } else {
        CHECK(proof.len == computed,
              "Proof size matches voleith_proof_byte_size");
        voleith_proof_free(&proof);
    }

    voleith_circuit_free(c);
}

/* ================================================================
 * Test: AND circuit prove + verify
 * ================================================================ */

static void
test_and_circuit_roundtrip(const voleith_params_t *params, const char *label)
{
    printf("\n[AND circuit roundtrip: %s]\n", label);

    voleith_circuit_t *c = build_and_circuit();
    if (!c) {
        printf("  SKIP: circuit alloc failed\n");
        return;
    }

    /* Witness: a=1, b=1 → a&b=1; instance c=1 → (a&b) XOR c = 0 ✓ */
    uint8_t witness[1] = {0x03};  /* bits: a=1, b=1 */
    uint8_t instance[1] = {0x01}; /* c=1 */
    uint8_t fs_seed[16];
    memset(fs_seed, 0xAB, sizeof(fs_seed));

    voleith_proof_t proof;
    memset(&proof, 0, sizeof(proof));
    int pret = voleith_prove(&proof, params, c, witness, instance, fs_seed,
                             sizeof(fs_seed));
    CHECK(pret == 0, "Prove succeeds");

    if (pret == 0) {
        int vret = voleith_verify(&proof, params, c, instance, fs_seed,
                                  sizeof(fs_seed));
        CHECK(vret == 0, "Valid proof verifies");
        voleith_proof_free(&proof);
    }

    voleith_circuit_free(c);
}

/* ================================================================
 * Test: Wrong witness is rejected
 * ================================================================ */

static void
test_wrong_witness_rejected(void)
{
    printf("\n[wrong witness rejected]\n");

    const voleith_params_t *params = &voleith_params_em_128f;
    voleith_circuit_t *c = build_and_circuit();
    if (!c) {
        printf("  SKIP: circuit alloc failed\n");
        return;
    }

    /* Correct witness: a=1, b=0, c=0 → (1&0) XOR 0 = 0 ✓ */
    uint8_t witness_ok[1] = {0x01}; /* a=1, b=0 */
    uint8_t instance[1] = {0x00};   /* c=0 */
    /* Wrong witness: a=1, b=1, but c=0 → (1&1) XOR 0 = 1 ✗ */
    uint8_t witness_bad[1] = {0x03}; /* a=1, b=1 */
    uint8_t fs_seed[16];
    memset(fs_seed, 0x77, sizeof(fs_seed));

    /* X-10: the bit-level prover now rejects an invalid witness
     * up-front (matching the GF(2⁸) discipline) - voleith_prove must
     * return non-zero and must not publish a proof.  Defense-in-
     * depth: even if the prover ever regresses to publish a bad
     * proof, the verifier still rejects it.
     */
    voleith_proof_t proof;
    memset(&proof, 0, sizeof(proof));

    int pret = voleith_prove(&proof, params, c, witness_bad, instance, fs_seed,
                             sizeof(fs_seed));
    CHECK(pret != 0, "X-10: prove with wrong witness is rejected upfront");
    if (pret == 0) {
        /* Should not be reached under the current contract, but if
         * the prover ever publishes a bad proof, the verifier still
         * catches it. */
        int vret = voleith_verify(&proof, params, c, instance, fs_seed,
                                  sizeof(fs_seed));
        CHECK(vret != 0, "verify rejects bad-witness proof (fallback)");
        voleith_proof_free(&proof);
    }

    /* Sanity: a correct witness still proves and verifies. */
    memset(&proof, 0, sizeof(proof));
    pret = voleith_prove(&proof, params, c, witness_ok, instance, fs_seed,
                         sizeof(fs_seed));
    CHECK(pret == 0, "Prove with correct witness succeeds");
    if (pret == 0) {
        int vret2 = voleith_verify(&proof, params, c, instance, fs_seed,
                                   sizeof(fs_seed));
        CHECK(vret2 == 0, "Correct witness verifies");
        voleith_proof_free(&proof);
    }

    voleith_circuit_free(c);
}

/* ================================================================
 * Test: Modified proof is rejected
 * ================================================================ */

static void
test_tamper_detection(void)
{
    printf("\n[tamper detection]\n");

    const voleith_params_t *params = &voleith_params_em_128f;
    voleith_circuit_t *c = build_and_circuit();
    if (!c) {
        printf("  SKIP: circuit alloc failed\n");
        return;
    }

    uint8_t witness[1] = {0x03};  /* a=1, b=1 */
    uint8_t instance[1] = {0x01}; /* c=1 */
    uint8_t fs_seed[16];
    memset(fs_seed, 0x55, sizeof(fs_seed));

    voleith_proof_t proof;
    memset(&proof, 0, sizeof(proof));
    int pret = voleith_prove(&proof, params, c, witness, instance, fs_seed,
                             sizeof(fs_seed));
    if (pret != 0) {
        printf("  SKIP: prove failed\n");
        voleith_circuit_free(c);
        return;
    }

    /* Verify clean proof passes */
    CHECK(voleith_verify(&proof, params, c, instance, fs_seed,
                         sizeof(fs_seed)) == 0,
          "Clean proof verifies before tampering");

    /* Test one byte from each logical proof section to confirm the verifier
     * actually checks every component. The Fiat-Shamir hash guarantee means
     * any change in a checked section propagates to chall_3 mismatch. */
    size_t proof_len = proof.len;
    uint8_t *proof_data = proof.data;
    int all_rejected = 1;

    /* Compute section offsets matching proof_layout() in proof.c */
    unsigned int nb = params->lambda / 8;
    size_t ell = voleith_qs_ell(c);
    size_t ellhat = voleith_qs_ellhat(c, params->lambda);
    size_t ellhat_bytes = (ellhat + 7) / 8;
    size_t ell_bytes = (ell + 7) / 8;
    size_t utilde_bytes = nb + 2; /* VOLEITH_VOLE_HASH_B = 2 */
    size_t decom_size =
        params->n_leafcom * params->tau * nb + params->T_open * nb;
    size_t off_c = 0;
    size_t off_utilde = off_c + (params->tau - 1) * ellhat_bytes;
    size_t off_d = off_utilde + utilde_bytes;
    size_t off_a1 = off_d + ell_bytes;
    size_t off_a2 = off_a1 + nb;
    size_t off_decom = off_a2 + nb;
    size_t off_chall3 = off_decom + decom_size;
    size_t off_iv = off_chall3 + nb;
    size_t off_ctr = off_iv + 16;

    /* One byte per section */
    size_t positions[] = {
        off_c,      /* c[0]: VOLE correction values */
        off_utilde, /* u_tilde: compressed VOLE */
        off_d,      /* d: witness correction (only if ell_bytes > 0) */
        off_a1,     /* a1_tilde: QS degree-1 hash */
        off_a2,     /* a2_tilde: QS degree-2 hash */
        off_decom,  /* decom_i: BAVC opening */
        off_chall3, /* chall_3: grinding challenge */
        off_iv,     /* iv: PRG initialisation vector */
        off_ctr,    /* ctr: grinding counter */
    };

    for (size_t pi = 0; pi < sizeof(positions) / sizeof(positions[0]); pi++) {
        size_t p = positions[pi];
        if (p >= proof_len)
            continue; /* section absent for this circuit */

        uint8_t orig = proof_data[p];
        proof_data[p] ^= 0xFF;

        voleith_proof_t tampered = {proof_data, proof_len};
        int vret = voleith_verify(&tampered, params, c, instance, fs_seed,
                                  sizeof(fs_seed));
        if (vret == 0) {
            printf("  FAIL: byte at section offset %zu not rejected\n", p);
            all_rejected = 0;
        }

        proof_data[p] = orig;
    }

    CHECK(all_rejected, "Each proof section byte is rejected when tampered");

    voleith_proof_free(&proof);
    voleith_circuit_free(c);
}

/* ================================================================
 * Test: Different fs_seeds give different but valid proofs
 * ================================================================ */

static void
test_different_seeds(void)
{
    printf("\n[different fs_seeds]\n");

    const voleith_params_t *params = &voleith_params_em_128f;
    voleith_circuit_t *c = build_and_circuit();
    if (!c) {
        printf("  SKIP\n");
        return;
    }

    uint8_t witness[1] = {0x03};
    uint8_t instance[1] = {0x01};
    uint8_t seed1[16], seed2[16];
    memset(seed1, 0x11, sizeof(seed1));
    memset(seed2, 0x22, sizeof(seed2));

    voleith_proof_t p1, p2;
    memset(&p1, 0, sizeof(p1));
    memset(&p2, 0, sizeof(p2));

    int r1 =
        voleith_prove(&p1, params, c, witness, instance, seed1, sizeof(seed1));
    int r2 =
        voleith_prove(&p2, params, c, witness, instance, seed2, sizeof(seed2));

    CHECK(r1 == 0 && r2 == 0, "Both proves succeed");

    if (r1 == 0 && r2 == 0) {
        CHECK(p1.len == p2.len, "Proof sizes match");
        CHECK(memcmp(p1.data, p2.data, p1.len) != 0,
              "Different seeds → different proofs");
        CHECK(voleith_verify(&p1, params, c, instance, seed1, sizeof(seed1)) ==
                  0,
              "Proof 1 verifies with seed1");
        CHECK(voleith_verify(&p2, params, c, instance, seed2, sizeof(seed2)) ==
                  0,
              "Proof 2 verifies with seed2");
        /* Cross-verify should fail */
        CHECK(voleith_verify(&p1, params, c, instance, seed2, sizeof(seed2)) !=
                  0,
              "Proof 1 rejected with seed2");
        voleith_proof_free(&p1);
        voleith_proof_free(&p2);
    }

    voleith_circuit_free(c);
}

/* ================================================================
 * Test: Chain circuit (more AND gates)
 * ================================================================ */

static void
test_chain_circuit(void)
{
    printf("\n[chain circuit: 8 AND gates]\n");

    const voleith_params_t *params = &voleith_params_em_128f;
    /* Circuit with 8 AND gates; witness a=0, b=0 → output 0 → assert_zero passes */
    voleith_circuit_t *c = build_chain_circuit(8);
    if (!c) {
        printf("  SKIP\n");
        return;
    }

    uint8_t witness[1] = {0x00}; /* a=0, b=0 */
    uint8_t fs_seed[16];
    memset(fs_seed, 0x33, sizeof(fs_seed));

    voleith_proof_t proof;
    memset(&proof, 0, sizeof(proof));
    int pret = voleith_prove(&proof, params, c, witness, NULL, fs_seed,
                             sizeof(fs_seed));
    CHECK(pret == 0, "Chain circuit prove succeeds");

    if (pret == 0) {
        int vret =
            voleith_verify(&proof, params, c, NULL, fs_seed, sizeof(fs_seed));
        CHECK(vret == 0, "Chain circuit verifies");
        voleith_proof_free(&proof);
    }

    voleith_circuit_free(c);
}

/* ================================================================
 * Main
 * ================================================================ */

/* ================================================================
 * X-7 regression: voleith_params_validate rejects every documented
 * malformed parameter shape, accepts the predefined parameter sets.
 * ================================================================ */

static void
test_params_validate(void)
{
    CHECK(voleith_params_validate(NULL) != 0, "X-7: NULL params rejected");

    /* All predefined static parameter sets must pass. */
    CHECK(voleith_params_validate(&voleith_params_em_128s) == 0,
          "X-7: em_128s accepted");
    CHECK(voleith_params_validate(&voleith_params_em_128f) == 0,
          "X-7: em_128f accepted");
    CHECK(voleith_params_validate(&voleith_params_em_192s) == 0,
          "X-7: em_192s accepted");
    CHECK(voleith_params_validate(&voleith_params_em_192f) == 0,
          "X-7: em_192f accepted");
    CHECK(voleith_params_validate(&voleith_params_em_256s) == 0,
          "X-7: em_256s accepted");
    CHECK(voleith_params_validate(&voleith_params_em_256f) == 0,
          "X-7: em_256f accepted");

    voleith_params_t p;

    /* Bad lambda. */
    p = voleith_params_em_128f;
    p.lambda = 64;
    CHECK(voleith_params_validate(&p) != 0, "X-7: lambda=64 rejected");
    p.lambda = 129;
    CHECK(voleith_params_validate(&p) != 0, "X-7: lambda=129 rejected");
    p.lambda = 0;
    CHECK(voleith_params_validate(&p) != 0, "X-7: lambda=0 rejected");

    /* Bad tau. */
    p = voleith_params_em_128f;
    p.tau = 0;
    CHECK(voleith_params_validate(&p) != 0, "X-7: tau=0 rejected");
    p.tau = 33;
    CHECK(voleith_params_validate(&p) != 0,
          "X-7: tau=33 rejected (exceeds i_delta[32])");
    p.tau = UINT_MAX;
    CHECK(voleith_params_validate(&p) != 0, "X-7: tau=UINT_MAX rejected");

    /* Bad w_grind. */
    p = voleith_params_em_128f;
    p.w_grind = p.lambda;
    CHECK(voleith_params_validate(&p) != 0,
          "X-7: w_grind == lambda rejected");
    p.w_grind = p.lambda + 1;
    CHECK(voleith_params_validate(&p) != 0, "X-7: w_grind > lambda rejected");
    p.w_grind = UINT_MAX;
    CHECK(voleith_params_validate(&p) != 0, "X-7: w_grind=UINT_MAX rejected");

    /* Bad n_leafcom. */
    p = voleith_params_em_128f;
    p.n_leafcom = 0;
    CHECK(voleith_params_validate(&p) != 0, "X-7: n_leafcom=0 rejected");
    p.n_leafcom = 1;
    CHECK(voleith_params_validate(&p) != 0, "X-7: n_leafcom=1 rejected");
    p.n_leafcom = 4;
    CHECK(voleith_params_validate(&p) != 0, "X-7: n_leafcom=4 rejected");

    /* Bad T_open. */
    p = voleith_params_em_128f;
    p.T_open = 0;
    CHECK(voleith_params_validate(&p) != 0, "X-7: T_open=0 rejected");
}

/* X-7: confirm the public prove / verify entry points surface the
 * validation failure with a clean -1, not a deep-cascade rejection. */
static void
test_params_validate_at_api_boundary(void)
{
    voleith_circuit_t *c = voleith_circuit_new();
    wire_id w = voleith_circuit_add_witness(c);
    voleith_circuit_assert_zero(c, w);

    uint8_t witness[1] = {0};
    uint8_t fs_seed[16] = {0};

    voleith_params_t bad = voleith_params_em_128f;
    bad.tau = 0; /* Invalid */

    size_t blob_size = voleith_commit_blob_size(&voleith_params_em_128f, c);
    uint8_t *blob = calloc(blob_size, 1);

    voleith_prover_commit_t *ctx = NULL;
    int rc = voleith_prove_commit(&ctx, &bad, c, witness, NULL, fs_seed,
                                  sizeof(fs_seed), blob);
    CHECK(rc != 0, "X-7: voleith_prove_commit rejects invalid params");

    voleith_proof_t proof = {NULL, voleith_proof_byte_size(
                                       &voleith_params_em_128f,
                                       voleith_qs_ell(c))};
    proof.data = calloc(proof.len, 1);
    voleith_verifier_reconstruct_t *vctx = NULL;
    int rc2 = voleith_verify_reconstruct(&vctx, &proof, &bad, c, blob);
    CHECK(rc2 != 0, "X-7: voleith_verify_reconstruct rejects invalid params");

    free(proof.data);
    free(blob);
    voleith_circuit_free(c);
}

int
main(void)
{
    printf("=== test_proof ===\n");

    test_vole_hash_tvs();
    test_proof_size();
    test_and_circuit_roundtrip(&voleith_params_em_128f, "em_128f");
    test_and_circuit_roundtrip(&voleith_params_em_128s, "em_128s");
    test_wrong_witness_rejected();
    test_tamper_detection();
    test_different_seeds();
    test_chain_circuit();
    test_params_validate();
    test_params_validate_at_api_boundary();

    printf("\n=== Results: %d passed, %d failed ===\n", g_pass, g_fail);
    return (g_fail > 0) ? 1 : 0;
}
