/*
 * Copyright (c) 2026 Jason Crawford
 * SPDX-License-Identifier: AGPL-3.0-only
 *
 * test_shipshape_reg_hash_grid.c - crypto-v2 hash-parametric registry
 * equivalence tests (MR2 acceptance gate).
 *
 * For each hash-parametric entry, every grid point's live body_hash
 * must equal the corresponding frozen table row.  This is the
 * in-process analog of the registry-diff CI gate: if the live builders
 * diverge from the frozen table, at least one of these checks fails.
 *
 * NOTE: this test will NOT link until parsers/shipshape_registry_table.c
 * has been regenerated by the freeze tool (it references
 * voleith_shipshape_reg_hash[] and voleith_shipshape_reg_hash_count,
 * which are emitted by the second pass added in MR2).  After MR2 source
 * lands, run:
 *
 *   cmake -S . -B build -DVOLEITH_BUILD_REGISTRY_FREEZE=ON
 *   cmake --build build --target shipshape_registry_freeze
 *   ./build/tools/shipshape_registry_freeze/shipshape_registry_freeze \
 *       > parsers/shipshape_registry_table.c
 *
 * then rebuild normally and this test will link and run.
 */

#include "gf8_circuit_fingerprint.h"
#include "shipshape_node_hash_types.h"
#include "shipshape_registry.h"

#include <stddef.h>
#include <stdint.h>
#include <stdio.h>
#include <string.h>

static int test_count = 0;
static int pass_count = 0;

static void
check(const char *name, int cond)
{
    test_count++;
    if (cond) {
        pass_count++;
    } else {
        printf("  FAIL: %s\n", name);
    }
}

int
main(void)
{
    size_t i, g, b;
    size_t hcount;
    char label[256];

    printf("test_shipshape_reg_hash_grid: starting\n");

    hcount = voleith_shipshape_reg_hash_descriptor_count();

    /*
     * Sanity: live descriptor count matches frozen table count.
     */
    snprintf(label, sizeof(label),
             "descriptor count matches frozen table count");
    check(label, hcount == voleith_shipshape_reg_hash_count);

    for (i = 0; i < hcount; i++) {
        const voleith_shipshape_reg_hash_entry_t *fe =
            &voleith_shipshape_reg_hash[i];
        voleith_shipshape_reg_hash_body_t live_grid[64];
        size_t live_n;
        const char *fqn = NULL;

        voleith_shipshape_reg_hash_descriptor(i, &fqn, NULL, NULL, NULL, NULL,
                                              NULL, NULL, NULL, NULL, NULL,
                                              NULL, NULL);

        live_n = voleith_shipshape_reg_hash_grid(i, live_grid, 64);

        /*
         * Grid size: live count matches frozen n_bodies.
         */
        snprintf(label, sizeof(label), "entry %zu (%s): grid size matches", i,
                 fqn ? fqn : "?");
        check(label, live_n == fe->n_bodies);

        for (g = 0; g < live_n && g < fe->n_bodies; g++) {
            uint8_t live_hash[VOLEITH_SHIPSHAPE_REGISTRY_BODY_HASH_BYTES];
            int rc;

            /*
             * Derive the live body hash for this grid point.
             */
            rc = voleith_shipshape_reg_hash_body_hash(
                i, live_grid[g].type_id, live_grid[g].params, live_hash);

            snprintf(label, sizeof(label),
                     "entry %zu (%s) grid[%zu] type_id=%u: body_hash ok", i,
                     fqn ? fqn : "?", g, live_grid[g].type_id);
            check(label, rc == 0);
            if (rc != 0)
                continue;

            /*
             * Compare live hash against frozen table row.
             */
            snprintf(label, sizeof(label),
                     "entry %zu (%s) grid[%zu] type_id=%u: "
                     "live == frozen hash",
                     i, fqn ? fqn : "?", g, live_grid[g].type_id);
            check(label,
                  memcmp(live_hash, fe->bodies[g].hash,
                         VOLEITH_SHIPSHAPE_REGISTRY_BODY_HASH_BYTES) == 0);

            /*
             * type_id and params must match between live grid and frozen row.
             */
            snprintf(label, sizeof(label),
                     "entry %zu (%s) grid[%zu]: type_id matches", i,
                     fqn ? fqn : "?", g);
            check(label, live_grid[g].type_id == fe->bodies[g].type_id);

            snprintf(label, sizeof(label),
                     "entry %zu (%s) grid[%zu]: params match", i,
                     fqn ? fqn : "?", g);
            {
                int params_ok = 1;
                for (b = 0; b < VOLEITH_SHIPSHAPE_REG_MAX_PARAMS; b++) {
                    if (live_grid[g].params[b] != fe->bodies[g].params[b])
                        params_ok = 0;
                }
                check(label, params_ok);
            }
        }

        /*
         * For hirose_fixed_32 rows (type_id == 7, fixed_leaf_bytes == 32):
         * verify that the effective leaf width is 32.
         *
         * merkle/path_secret and ring_sig/v1: params[leaf_param] == 32.
         * indexed_merkle/nonmember_secret (n_params==3): 2*tb + ib == 32.
         */
        {
            uint8_t n_params_e = 0, leaf_param = 0;
            voleith_shipshape_reg_hash_descriptor(
                i, NULL, NULL, NULL, NULL, &n_params_e, NULL, &leaf_param, NULL,
                NULL, NULL, NULL, NULL);

            for (g = 0; g < fe->n_bodies; g++) {
                uint32_t eff_leaf;

                if (fe->bodies[g].type_id !=
                    VOLEITH_SHIPSHAPE_NHT_HIROSE_FIXED_32)
                    continue;
                if (n_params_e == 3) {
                    /* indexed_merkle: leaf record = 2*tb + ib */
                    eff_leaf =
                        2u * fe->bodies[g].params[0] + fe->bodies[g].params[1];
                } else {
                    eff_leaf = fe->bodies[g].params[leaf_param];
                }
                snprintf(label, sizeof(label),
                         "entry %zu (%s) grid[%zu] hirose_fixed_32: "
                         "effective leaf width == 32",
                         i, fqn ? fqn : "?", g);
                check(label, eff_leaf == 32u);
            }
        }
    }

    printf("test_shipshape_reg_hash_grid: %d/%d passed\n", pass_count,
           test_count);
    return (pass_count == test_count) ? 0 : 1;
}
