/*
 * Copyright (c) 2026 Jason Crawford
 * SPDX-License-Identifier: AGPL-3.0-only
 *
 * shipshape_registry.h - crypto-v1 Tier 2a registry: types, frozen table,
 * and the live standalone-body builders.
 *
 * The Shipshape Tier 2a registry (the Shipshape spec §7, the stdlib spec)
 * is a closed set of cryptographic subcircuits, each pinned by a body hash.
 * Two artifacts live here:
 *
 *   - The FROZEN table (parsers/shipshape_registry_table.c, GENERATED by
 *     tools/shipshape_registry_freeze): a const array of every entry's FQN,
 *     kind, signature string, parameter bounds, and frozen body hash(es).
 *     The parser links it for name lookup and dispatch authentication.
 *
 *   - The LIVE builders (parsers/shipshape_registry_build.c, hand-written):
 *     the descriptor table that maps each entry to its C circuit builder,
 *     plus voleith_shipshape_registry_build_standalone(), which constructs the
 *     D3 standalone-witness circuit whose fingerprint IS the body hash.
 *     The freeze tool reads the descriptors to regenerate the table; CI
 *     re-derives and diffs, and divergence is a release-blocker
 *     (the stdlib spec §3, D2, D7).
 *
 * Body hash construction (D3): build a fresh GF(2^8) circuit, add each
 * signature INPUT wire as a WITNESS wire in signature order, emit the
 * body, then take voleith_gf8_circuit_fingerprint() of the result.  No
 * new hash machinery; the fingerprint already pins the full canonical
 * wire and constraint tables.
 */

#ifndef VOLEITH_SHIPSHAPE_REGISTRY_H
#define VOLEITH_SHIPSHAPE_REGISTRY_H

#include <stddef.h>
#include <stdint.h>

#include "gf8_circuit.h"
#include "gf8_circuit_fingerprint.h"
#include "node_hash_vt.h"

/* A body hash is exactly a GF(2^8) circuit fingerprint (16 bytes). */
#define VOLEITH_SHIPSHAPE_REGISTRY_BODY_HASH_BYTES                             \
    VOLEITH_GF8_CIRCUIT_FINGERPRINT_BYTES

typedef enum {
    VOLEITH_SHIPSHAPE_REG_FIXED = 0,
    VOLEITH_SHIPSHAPE_REG_PARAMETRIC = 1,
    VOLEITH_SHIPSHAPE_REG_HASH_PARAM = 2
} voleith_shipshape_reg_kind_t;

/*
 * One frozen (parameter, body-hash) pair.  FIXED entries carry exactly
 * one with param == 0 (ignored).  PARAMETRIC entries carry the frozen
 * grid: one pair per parameter value the freeze tool snapshots.
 */
typedef struct {
    uint32_t param;
    uint8_t hash[VOLEITH_SHIPSHAPE_REGISTRY_BODY_HASH_BYTES];
} voleith_shipshape_reg_body_t;

/*
 * One registry entry.  param_min / param_max are the inclusive bounds
 * on the inferred length parameter for PARAMETRIC entries (FIXED: both
 * 0).  bodies points at the frozen grid (n_bodies >= 1).
 */
typedef struct {
    const char *fqn;
    voleith_shipshape_reg_kind_t kind;
    const char *signature;
    uint32_t param_min;
    uint32_t param_max;
    const voleith_shipshape_reg_body_t *bodies;
    size_t n_bodies;
} voleith_shipshape_reg_entry_t;

/*
 * The frozen crypto-v1 table (parsers/shipshape_registry_table.c, generated).
 * voleith_shipshape_registry_count entries, in canonical order.
 */
extern const voleith_shipshape_reg_entry_t voleith_shipshape_registry[];
extern const size_t voleith_shipshape_registry_count;

/* ================================================================
 * Live builders (parsers/shipshape_registry_build.c)
 * ================================================================ */

/*
 * Number of live registry descriptors.  Equals voleith_shipshape_registry_count
 * whenever the frozen table is in sync with the builders.
 */
size_t voleith_shipshape_registry_descriptor_count(void);

/*
 * Live descriptor metadata for entry idx (consumed by the freeze tool
 * and the consistency tests).  Any out pointer may be NULL.  Returns 0
 * on success, -1 if idx is out of range.
 */
int voleith_shipshape_registry_descriptor(size_t idx, const char **fqn,
                                          voleith_shipshape_reg_kind_t *kind,
                                          const char **signature,
                                          uint32_t *param_min,
                                          uint32_t *param_max);

/*
 * The freeze grid for entry idx: the parameter values whose body hashes
 * are frozen into the table.  Writes up to max values into out (out may
 * be NULL to query only) and returns the grid size.  FIXED entries
 * return 1 with out[0] == 0.  Returns 0 if idx is out of range.
 */
size_t voleith_shipshape_registry_grid(size_t idx, uint32_t *out, size_t max);

/* Every crypto-v1 signature has at most this many input arguments. */
/* Bumped from 2 to 7 for crypto-v2: indexed_merkle/nonmember_secret has 7. */
#define VOLEITH_SHIPSHAPE_REGISTRY_MAX_INPUTS 7

/* Maximum number of inferred parameters for a REG_HASH_PARAM entry. */
#define VOLEITH_SHIPSHAPE_REG_MAX_PARAMS 3

/*
 * Sentinel in an in_len slot marking the argument whose actual length
 * supplies the entry's inferred parameter n (the Shipshape spec 7.1).
 * FIXED entries have no such slot; PARAMETRIC entries have exactly one.
 */
#define VOLEITH_SHIPSHAPE_REGISTRY_PARAM_LEN UINT32_MAX

/*
 * Signature layout of entry idx, for call-site lowering: the number of
 * input arguments, each argument's element count (in_len, with
 * VOLEITH_SHIPSHAPE_REGISTRY_PARAM_LEN marking the inferred-parameter
 * slot), and the single output's element count and vector-ness (every
 * crypto-v1 entry has exactly one output; a scalar output has
 * out_len == 1 and *out_is_vector == 0).  Any out pointer may be NULL.
 * Returns 0 on success, -1 if idx is out of range.
 */
int voleith_shipshape_registry_signature(
    size_t idx, size_t *n_inputs,
    uint32_t in_len[VOLEITH_SHIPSHAPE_REGISTRY_MAX_INPUTS], uint32_t *out_len,
    int *out_is_vector);

/*
 * Instantiation cost of entry idx at parameter param, from the normative
 * the Shipshape spec 7.2 formulas: *blocks receives the derived block
 * count (AES calls for cmac/<...>, compressions for grostl/<...>; 1 for FIXED
 * entries) and *invs the INV count, which equals the witness slots the
 * body adds.  The parser checks blocks against MAX_BLOCKS_PER_OPCODE and
 * uses invs as a lower bound on the wire growth, both before emitting
 * any gate.  Either out pointer may be NULL.  Returns 0 on success, -1
 * if idx is out of range.
 */
int voleith_shipshape_registry_cost(size_t idx, uint32_t param, size_t *blocks,
                                    size_t *invs);

/*
 * Emit the canonical body of entry idx at parameter param into circuit
 * c over caller-supplied wires (ISA 5.2 Step 1): `in` holds the input
 * arguments' wires concatenated in signature order (total length per
 * voleith_shipshape_registry_signature with param substituted), and the
 * output's wires are written to `out` (out_len entries).  The gate
 * sequence is byte-for-byte the one the hand-written circuits/ builder
 * emits (Goal 2(iii) / STDLIB D2 structural identity).
 *
 * Returns 0 on success, -1 on allocation failure (the circuit may hold
 * a partial body; the caller discards it) or if idx is out of range.
 */
int voleith_shipshape_registry_inline(size_t idx, voleith_gf8_circuit_t *c,
                                      const gf8_wire_id *in, uint32_t param,
                                      gf8_wire_id *out);

/*
 * Build the D3 standalone-witness circuit for entry idx at parameter
 * param: each signature input wire added as a WITNESS in signature
 * order, then the body emitted by the corresponding C builder.  The
 * fingerprint of the returned circuit is the entry's body hash at param.
 *
 * param is ignored for FIXED entries.  For PARAMETRIC entries it is the
 * inferred vector length (message or input bytes).
 *
 * Returns a newly allocated circuit (free with voleith_gf8_circuit_free)
 * or NULL on allocation failure or if idx is out of range.
 */
voleith_gf8_circuit_t *
voleith_shipshape_registry_build_standalone(size_t idx, uint32_t param);

/*
 * Convenience: build the standalone circuit for entry idx at param and
 * write its body hash (gf8 fingerprint) to out.  Returns 0 on success,
 * -1 on error.
 */
int voleith_shipshape_registry_body_hash(
    size_t idx, uint32_t param,
    uint8_t out[VOLEITH_SHIPSHAPE_REGISTRY_BODY_HASH_BYTES]);

/* ================================================================
 * Crypto-v2 hash-parametric registry (REG_HASH_PARAM).
 *
 * These entries accept a node-hash type selector (merkle/path_secret,
 * indexed_merkle/nonmember_secret, ring_sig/v1) and are frozen as a
 * parallel table to the crypto-v1 FIXED/PARAMETRIC table above.
 * See the crypto-v2 implementation plan MR2.
 * ================================================================ */

/*
 * Per-argument length specification for hash-parametric entries.
 * FIXED:            the argument has exactly `value` wires.
 * PARAM:            the argument has `params[value]` wires.
 * DEPTH_TIMES_NODE: the argument has `params[depth_param]*node_bytes` wires.
 */
typedef enum {
    SS_ARGLEN_FIXED = 0, /* exact constant `value` wires            */
    SS_ARGLEN_PARAM = 1, /* free param index `value`                */
    SS_ARGLEN_DEPTH_TIMES_NODE =
        2,             /* == params[depth_param]*node_bytes       */
    SS_ARGLEN_NODE = 3 /* exactly vt->node_bytes wires            */
} ss_arglen_kind_t;

typedef struct {
    ss_arglen_kind_t kind;
    uint32_t value;
} ss_arglen_t;

/* One frozen (type, param-tuple) -> body-hash row. */
typedef struct {
    uint16_t type_id;
    uint32_t params[VOLEITH_SHIPSHAPE_REG_MAX_PARAMS];
    uint8_t n_params;
    uint8_t hash[VOLEITH_SHIPSHAPE_REGISTRY_BODY_HASH_BYTES];
} voleith_shipshape_reg_hash_body_t;

/* One frozen hash-parametric registry entry. */
typedef struct {
    const char *fqn;
    const char *signature;
    const uint16_t *types;
    size_t n_types;
    uint8_t n_params;
    uint8_t depth_param; /* index in params[] holding depth */
    uint8_t leaf_param;  /* index in params[] for leaf/sk width */
    uint32_t param_min[VOLEITH_SHIPSHAPE_REG_MAX_PARAMS];
    uint32_t param_max[VOLEITH_SHIPSHAPE_REG_MAX_PARAMS];
    uint8_t n_inputs;
    ss_arglen_t in[VOLEITH_SHIPSHAPE_REGISTRY_MAX_INPUTS];
    uint8_t out_is_node_vec; /* 1: output = node bytes; 0: none */
    const voleith_shipshape_reg_hash_body_t *bodies;
    size_t n_bodies;
} voleith_shipshape_reg_hash_entry_t;

/*
 * The frozen crypto-v2 hash-parametric table
 * (parsers/shipshape_registry_table.c, generated).
 */
extern const voleith_shipshape_reg_hash_entry_t voleith_shipshape_reg_hash[];
extern const size_t voleith_shipshape_reg_hash_count;

/* ================================================================
 * Live hash-parametric accessors (parsers/shipshape_registry_build.c)
 * ================================================================ */

/* Number of live hash-parametric descriptors. */
size_t voleith_shipshape_reg_hash_descriptor_count(void);

/*
 * Metadata for hash-parametric entry idx.  Any out pointer may be NULL.
 * Returns 0 on success, -1 if idx is out of range.
 */
int voleith_shipshape_reg_hash_descriptor(
    size_t idx, const char **fqn, const char **signature,
    const uint16_t **types, size_t *n_types, uint8_t *n_params,
    uint8_t *depth_param, uint8_t *leaf_param,
    uint32_t param_min[VOLEITH_SHIPSHAPE_REG_MAX_PARAMS],
    uint32_t param_max[VOLEITH_SHIPSHAPE_REG_MAX_PARAMS], uint8_t *n_inputs,
    ss_arglen_t in[VOLEITH_SHIPSHAPE_REGISTRY_MAX_INPUTS],
    uint8_t *out_is_node_vec);

/*
 * Freeze grid for entry idx: writes up to max (type_id, params[]) rows
 * into out (hash field is unused on output rows).  Returns the grid size,
 * or 0 if idx is out of range.
 */
size_t voleith_shipshape_reg_hash_grid(size_t idx,
                                       voleith_shipshape_reg_hash_body_t *out,
                                       size_t max);

/*
 * Instantiation cost for entry idx at (vt, params): *blocks receives the
 * derived block count, *invs the INV count (witness wire lower bound).
 * Either out pointer may be NULL.  Returns 0 on success, -1 if out of range.
 */
int voleith_shipshape_reg_hash_cost(size_t idx, const voleith_node_hash_vt *vt,
                                    const uint32_t *params, size_t *blocks,
                                    size_t *invs);

/*
 * Emit the canonical body of entry idx over caller-supplied wires `in`
 * (flatten order from the signature), writing outputs to `out`
 * (out_is_node_vec == 0 entries may pass NULL for out).
 * Returns 0 on success, -1 on error.
 */
int voleith_shipshape_reg_hash_inline(size_t idx, voleith_gf8_circuit_t *c,
                                      const voleith_node_hash_vt *vt,
                                      const uint32_t *params,
                                      const gf8_wire_id *in, gf8_wire_id *out);

/*
 * D3 standalone-witness circuit for entry idx at (type_id, params):
 * adds all signature inputs as WITNESS wires in signature order, then
 * inlines the body.  The circuit fingerprint is the frozen body hash.
 * Returns a newly allocated circuit or NULL on error.
 */
voleith_gf8_circuit_t *
voleith_shipshape_reg_hash_build_standalone(size_t idx, uint16_t type_id,
                                            const uint32_t *params);

/*
 * Build the standalone circuit for entry idx at (type_id, params) and
 * write its body hash to out.  Returns 0 on success, -1 on error.
 */
int voleith_shipshape_reg_hash_body_hash(
    size_t idx, uint16_t type_id, const uint32_t *params,
    uint8_t out[VOLEITH_SHIPSHAPE_REGISTRY_BODY_HASH_BYTES]);

#endif /* VOLEITH_SHIPSHAPE_REGISTRY_H */
