/*
 * Copyright (c) 2026 Jason Crawford
 * SPDX-License-Identifier: AGPL-3.0-only
 *
 * fuzz_rs_unpack.c - libFuzzer harness for voleith_rs_sig_unpack, the
 * "VRSC" envelope parser (1.8.0 security review, recommended follow-up:
 * "Fuzz voleith_rs_sig_unpack ... (malformed blob) under a sanitizer").
 *
 * The packed blob travels on the wire and is fully attacker-controlled.
 * unpack reads the magic, format version, two fingerprints and a 4-byte
 * big-endian length, then mallocs and copies the inner proof.  This harness
 * feeds arbitrary bytes against the fixed reference cfg/params and frees any
 * successful result.  Random bytes rarely clear the constant-time
 * fingerprint check, so coverage of the post-fingerprint malloc/copy comes
 * from the committed valid seed (regenerated by fuzz_rs_seedgen); the header
 * parsing and every rejection branch are exercised directly.
 *
 * Build with -DVOLEITH_FUZZ=ON (Clang); see fuzz/README.md.
 */

#include <stddef.h>
#include <stdint.h>

#include "fuzz_rs_common.h"

int
LLVMFuzzerTestOneInput(const uint8_t *data, size_t size)
{
    voleith_rs_config_t cfg;
    voleith_params_t params = voleith_params_em_128f;
    voleith_rs_sig_t sig;
    voleith_rs_sig_unpacker_t *u = NULL;

    fuzz_rs_make_cfg(&cfg);

    /* Legacy one-shot path (reads v1 and v2). */
    if (voleith_rs_sig_unpack(&sig, data, size, &cfg, &params) == 0)
        voleith_rs_sig_free(&sig);

    /* Streaming reader path: exercise init + the section getters (v2 framing
     * loop, opener/generic lookups) directly. */
    if (voleith_rs_sig_unpack_init(&u, data, size, &cfg, &params) == 0) {
        const uint8_t *payload = NULL;
        size_t plen = 0;
        voleith_rs_sig_t s2;

        (void)voleith_rs_sig_unpack_opener(u, &payload, &plen);
        (void)voleith_rs_sig_unpack_section(u, 0x10u, &payload, &plen);
        if (voleith_rs_sig_unpack_proof(u, &s2) == 0)
            voleith_rs_sig_free(&s2);
        voleith_rs_sig_unpack_free(u);
    }

    return 0;
}
