/*
 * Copyright (c) 2026 Jason Crawford
 * SPDX-License-Identifier: AGPL-3.0-only
 *
 * fuzz_rs_verify.c - libFuzzer harness for voleith_rs_verify (1.8.0
 * security review, recommended follow-up: "Fuzz ... voleith_rs_verify
 * (malformed ... instance) under a sanitizer").
 *
 * The signature bytes are attacker-controlled at verify time.  This harness
 * fixes the cfg, params, public instance and message (the trusted side),
 * rebuilds the reference ring once in LLVMFuzzerInitialize, and feeds
 * arbitrary bytes as the inner proof (sig->data).  voleith_rs_verify must
 * stay memory-safe and return -1 on any malformed proof; the committed valid
 * seed (regenerated by fuzz_rs_seedgen) drives coverage of the deep verifier
 * path past the proof-header parse.
 *
 * The fuzz bytes are copied into an exact-size malloc buffer so
 * AddressSanitizer can catch a one-past-the-end read inside the verifier.
 *
 * Build with -DVOLEITH_FUZZ=ON (Clang); see fuzz/README.md.
 */

#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>
#include <string.h>

#include "fuzz_rs_common.h"

/* Reference configuration, rebuilt once.  Storage for the ring outlives
 * every input (pub borrows root). */
static voleith_rs_config_t g_cfg;
static voleith_params_t g_params;
static voleith_rs_public_t g_pub;
static uint8_t g_root[MERKLE_VT_MAX_NODE_BYTES];
static int g_ready;

int
LLVMFuzzerInitialize(int *argc, char ***argv)
{
    uint8_t sks[FUZZ_RS_N_MEMBERS * FUZZ_RS_SK_BYTES];
    /* depth_m * node_bytes per member; MERKLE_VT_MAX_NODE_BYTES is a safe
     * upper bound for the AES-DM 16-byte node. */
    static uint8_t
        sib[FUZZ_RS_N_MEMBERS * FUZZ_RS_DEPTH_M * MERKLE_VT_MAX_NODE_BYTES];
    voleith_rs_path_t paths[FUZZ_RS_N_MEMBERS];

    (void)argc;
    (void)argv;

    g_params = voleith_params_em_128f;
    fuzz_rs_make_cfg(&g_cfg);
    fuzz_rs_fill_sks(sks);

    if (voleith_rs_ring_build(&g_cfg, sks, NULL, FUZZ_RS_N_MEMBERS, g_root,
                              paths, sib) != 0)
        return 0; /* g_ready stays 0; harness no-ops */

    memset(&g_pub, 0, sizeof(g_pub));
    g_pub.membership_root = g_root;
    g_ready = 1;
    return 0;
}

int
LLVMFuzzerTestOneInput(const uint8_t *data, size_t size)
{
    voleith_rs_sig_t sig;
    uint8_t *copy;

    if (!g_ready)
        return 0;

    /* Exact-size copy: the verifier reads sig->data; an over-read lands in
     * ASan-poisoned memory rather than the adjacent fuzz buffer. */
    copy = malloc(size != 0 ? size : 1);
    if (copy == NULL)
        return 0;
    memcpy(copy, data, size);

    sig.data = copy;
    sig.len = size;

    (void)voleith_rs_verify(&sig, &g_cfg, &g_params, &g_pub,
                            (const uint8_t *)FUZZ_RS_MESSAGE,
                            FUZZ_RS_MESSAGE_LEN);

    free(copy);
    return 0;
}
