/*
 * Copyright (c) 2026 Jason Crawford
 * SPDX-License-Identifier: AGPL-3.0-only
 *
 * shipshape_registry_freeze.c - regenerate the frozen Tier 2a registry
 * table (parsers/shipshape_registry_table.c).
 *
 * Reads the live descriptors from parsers/shipshape_registry_build.c,
 * builds the D3 standalone-witness circuit for every FIXED body and every
 * parameter-grid point of every PARAMETRIC body, fingerprints each, and
 * emits the generated C table to stdout.  A second pass does the same
 * for the crypto-v2 hash-parametric entries.  Determinism: the builders
 * and the fingerprint are pure, so two runs produce byte-identical output.
 *
 *   ./shipshape_registry_freeze > parsers/shipshape_registry_table.c
 *
 * docs/CIRC_STDLIB.md §3 (freeze process), D2, D3, D7;
 * docs/SHIPSHAPE_IMPLEMENTATION_PLAN.md W2.1.
 */

#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>

#include "shipshape_registry.h"

#define MAX_GRID 64
/* MAX_HASH_GRID covers the largest hash-parametric grid (merkle/path_secret
 * has 30 points; indexed and ring_sig have 16 each -- all within 64). */
#define MAX_HASH_GRID 64

static const char *
kind_token(voleith_shipshape_reg_kind_t kind)
{
    return (kind == VOLEITH_SHIPSHAPE_REG_FIXED)
               ? "VOLEITH_SHIPSHAPE_REG_FIXED"
               : "VOLEITH_SHIPSHAPE_REG_PARAMETRIC";
}

static void
emit_header(void)
{
    printf("/*\n");
    printf(" * Copyright (c) 2026 Jason Crawford\n");
    printf(" * SPDX-License-Identifier: AGPL-3.0-only\n");
    printf(" *\n");
    printf(" * shipshape_registry_table.c - frozen crypto-v1 Tier 2a registry "
           "table.\n");
    printf(" *\n");
    printf(" * GENERATED by tools/shipshape_registry_freeze.  DO NOT EDIT BY "
           "HAND.\n");
    printf(" * Regenerate:\n");
    printf(" *   cmake -S . -B build -DVOLEITH_BUILD_REGISTRY_FREEZE=ON\n");
    printf(" *   cmake --build build --target shipshape_registry_freeze\n");
    printf(" *   "
           "./build/tools/shipshape_registry_freeze/shipshape_registry_freeze "
           "\\\n");
    printf(" *       > parsers/shipshape_registry_table.c\n");
    printf(" *\n");
    printf(" * crypto-v1 (SHIPSHAPE_SPEC.md §7.2).\n");
    printf(" */\n\n");
    printf("#include \"shipshape_registry.h\"\n\n");
    /* This is generated output, not hand-written source: keep clang-format
     * from rewrapping the hash byte tables so the checked-in copy stays
     * byte-identical to a fresh run (the W2.3 registry-diff gate). */
    printf("/* clang-format off */\n\n");
}

/* Print one bodies array for entry idx. */
static int
emit_bodies(size_t idx)
{
    uint32_t grid[MAX_GRID];
    size_t n = voleith_shipshape_registry_grid(idx, grid, MAX_GRID);
    if (n == 0 || n > MAX_GRID) {
        fprintf(stderr,
                "shipshape_registry_freeze: entry %zu grid size %zu out of "
                "range\n",
                idx, n);
        return -1;
    }

    printf("static const voleith_shipshape_reg_body_t bodies_%zu[] = {\n", idx);
    for (size_t g = 0; g < n; g++) {
        uint8_t hash[VOLEITH_SHIPSHAPE_REGISTRY_BODY_HASH_BYTES];
        if (voleith_shipshape_registry_body_hash(idx, grid[g], hash) != 0) {
            fprintf(
                stderr,
                "shipshape_registry_freeze: failed to build entry %zu param "
                "%u\n",
                idx, grid[g]);
            return -1;
        }
        printf("    {%u, {", grid[g]);
        for (size_t b = 0; b < VOLEITH_SHIPSHAPE_REGISTRY_BODY_HASH_BYTES; b++)
            printf("%s0x%02x", (b == 0) ? "" : ", ", hash[b]);
        printf("}},\n");
    }
    printf("};\n");
    return 0;
}

/* Print one hash-parametric bodies array for entry hidx. */
static int
emit_hash_bodies(size_t hidx)
{
    voleith_shipshape_reg_hash_body_t grid[MAX_HASH_GRID];
    size_t n = voleith_shipshape_reg_hash_grid(hidx, grid, MAX_HASH_GRID);
    size_t g, b;

    if (n == 0 || n > MAX_HASH_GRID) {
        fprintf(stderr,
                "shipshape_registry_freeze: hash entry %zu grid size %zu out "
                "of range\n",
                hidx, n);
        return -1;
    }

    printf("static const voleith_shipshape_reg_hash_body_t "
           "hash_bodies_%zu[] = {\n",
           hidx);
    for (g = 0; g < n; g++) {
        uint8_t hash[VOLEITH_SHIPSHAPE_REGISTRY_BODY_HASH_BYTES];
        if (voleith_shipshape_reg_hash_body_hash(hidx, grid[g].type_id,
                                                 grid[g].params, hash) != 0) {
            fprintf(stderr,
                    "shipshape_registry_freeze: failed to build hash entry "
                    "%zu type_id %u\n",
                    hidx, grid[g].type_id);
            return -1;
        }
        printf("    {%u, {", grid[g].type_id);
        for (b = 0; b < VOLEITH_SHIPSHAPE_REG_MAX_PARAMS; b++)
            printf("%s%uu", (b == 0) ? "" : ", ", grid[g].params[b]);
        printf("}, %u, {", grid[g].n_params);
        for (b = 0; b < VOLEITH_SHIPSHAPE_REGISTRY_BODY_HASH_BYTES; b++)
            printf("%s0x%02x", (b == 0) ? "" : ", ", hash[b]);
        printf("}},\n");
    }
    printf("};\n");
    return 0;
}

int
main(void)
{
    size_t count = voleith_shipshape_registry_descriptor_count();
    size_t hcount = voleith_shipshape_reg_hash_descriptor_count();
    size_t i;

    emit_header();

    /* Pass 1: crypto-v1 FIXED / PARAMETRIC entries. */
    for (i = 0; i < count; i++) {
        if (emit_bodies(i) != 0)
            return 1;
    }
    printf("\n");

    printf("const voleith_shipshape_reg_entry_t voleith_shipshape_registry[] = "
           "{\n");
    for (i = 0; i < count; i++) {
        const char *fqn = NULL, *sig = NULL;
        voleith_shipshape_reg_kind_t kind = VOLEITH_SHIPSHAPE_REG_FIXED;
        uint32_t pmin = 0, pmax = 0;
        if (voleith_shipshape_registry_descriptor(i, &fqn, &kind, &sig, &pmin,
                                                  &pmax) != 0) {
            fprintf(stderr, "shipshape_registry_freeze: bad descriptor %zu\n",
                    i);
            return 1;
        }
        size_t nbod = voleith_shipshape_registry_grid(i, NULL, 0);
        printf("    {\"%s\", %s,\n", fqn, kind_token(kind));
        printf("     \"%s\", %uu, %uu, bodies_%zu, %zu},\n", sig, pmin, pmax, i,
               nbod);
    }
    printf("};\n\n");

    printf("const size_t voleith_shipshape_registry_count =\n");
    printf("    sizeof(voleith_shipshape_registry) / "
           "sizeof(voleith_shipshape_registry[0]);\n\n");

    /* Pass 2: crypto-v2 hash-parametric entries. */
    for (i = 0; i < hcount; i++) {
        if (emit_hash_bodies(i) != 0)
            return 1;
    }
    printf("\n");

    printf("const voleith_shipshape_reg_hash_entry_t "
           "voleith_shipshape_reg_hash[] = {\n");
    for (i = 0; i < hcount; i++) {
        const char *fqn = NULL, *sig = NULL;
        const uint16_t *types = NULL;
        size_t n_types = 0;
        uint8_t n_params = 0, depth_param = 0, leaf_param = 0;
        uint32_t pmin[VOLEITH_SHIPSHAPE_REG_MAX_PARAMS];
        uint32_t pmax[VOLEITH_SHIPSHAPE_REG_MAX_PARAMS];
        uint8_t n_inputs = 0, out_is_node_vec = 0;
        ss_arglen_t in_spec[VOLEITH_SHIPSHAPE_REGISTRY_MAX_INPUTS];
        size_t nbod, j;

        if (voleith_shipshape_reg_hash_descriptor(
                i, &fqn, &sig, &types, &n_types, &n_params, &depth_param,
                &leaf_param, pmin, pmax, &n_inputs, in_spec,
                &out_is_node_vec) != 0) {
            fprintf(stderr,
                    "shipshape_registry_freeze: bad hash descriptor %zu\n", i);
            return 1;
        }
        nbod = voleith_shipshape_reg_hash_grid(i, NULL, 0);

        printf("    {\"%s\",\n", fqn);
        printf("     \"%s\",\n", sig);
        printf("     (const uint16_t []){");
        for (j = 0; j < n_types; j++)
            printf("%s%u", (j == 0) ? "" : ", ", types[j]);
        printf("}, %zu,\n", n_types);
        printf("     %u, %u, %u,\n", n_params, depth_param, leaf_param);
        printf("     {");
        for (j = 0; j < VOLEITH_SHIPSHAPE_REG_MAX_PARAMS; j++)
            printf("%s%uu", (j == 0) ? "" : ", ", pmin[j]);
        printf("}, {");
        for (j = 0; j < VOLEITH_SHIPSHAPE_REG_MAX_PARAMS; j++)
            printf("%s%uu", (j == 0) ? "" : ", ", pmax[j]);
        printf("},\n");
        printf("     %u, {", n_inputs);
        for (j = 0; j < VOLEITH_SHIPSHAPE_REGISTRY_MAX_INPUTS; j++) {
            printf("%s{%d, %uu}", (j == 0) ? "" : ", ", in_spec[j].kind,
                   in_spec[j].value);
        }
        printf("},\n");
        printf("     %u,\n", out_is_node_vec);
        printf("     hash_bodies_%zu, %zu},\n", i, nbod);
    }
    printf("};\n\n");

    printf("const size_t voleith_shipshape_reg_hash_count =\n");
    printf("    sizeof(voleith_shipshape_reg_hash) / "
           "sizeof(voleith_shipshape_reg_hash[0]);\n");

    printf("\n/* clang-format on */\n");

    return 0;
}
